# Generated by Django 3.2.7 on 2021-09-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_eco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statements',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
